# Always display username
[username]
# The format for how the username is displayed in the prompt
format = " via [$user](bold blue) "
# To show the username at all times, set `show_always` to true
show_always = true

# Always display time
[time]
# Display the time at all times
disabled = true
# Custom format for the time
format = "at [ğŸ•’ $time](bold green) "
# You can customize the time format string according to your preference
time_format = "%T"


# Language/tool-specific settings
[golang]
symbol = "ğŸ¹ "
style = "bold cyan"
format = "via [$symbol$version](bold cyan) "

[python]
symbol = "ğŸ "
style = "bold green"
format = "via [$symbol$version](bold green) "

[git_branch]
symbol = "ï˜ "
style = "bold purple"
#
# [git_status]
# conflicted = "âš”ï¸ "
# ahead = "â†‘"
# behind = "â†“"
# diverged = "ğŸ”€"
# untracked = "ğŸŸ¡"
# stashed = "ğŸ“¦"
# modified = "ğŸ“"
# staged = "ğŸš€"
# renamed = "ğŸ‘‘"
# deleted = "ğŸ—‘ï¸ "
